DROP TABLE IF EXISTS "Photo";
DROP TABLE IF EXISTS "Edge";
DROP TABLE IF EXISTS "EdgeType";
DROP TABLE IF EXISTS "ROIPOI";
DROP TABLE IF EXISTS "POI";
DROP TABLE IF EXISTS "Category";
DROP TABLE IF EXISTS "ROI";
DROP TABLE IF EXISTS "Building";

CREATE TABLE IF NOT EXISTS "Building"(
	id INT PRIMARY KEY,
	uuid VARCHAR(255) UNIQUE,
	major INT UNIQUE,
	name VARCHAR(255),
	description VARCHAR(2000),
	"openingHours" VARCHAR(255),
	address VARCHAR(255),
	"mapVersion" VARCHAR(255),
	"mapSize" VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS "ROI"(
	id INT PRIMARY KEY,
	uuid VARCHAR(255),
	major INT,
	minor INT UNIQUE,
	FOREIGN KEY (uuid) REFERENCES "Building"(uuid) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY (major) REFERENCES "Building"(major) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Category"(
	id INT PRIMARY KEY,
	description VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS "POI"(
	id INT PRIMARY KEY,
	name VARCHAR(255),
	description VARCHAR(2000),
	"categoryId" INT,
	FOREIGN KEY ("categoryId") REFERENCES "Category"(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "ROIPOI"(
	"ROIId" INT,
	"POIId" INT,
	PRIMARY KEY ("ROIId", "POIId"),
	FOREIGN KEY ("ROIId") REFERENCES "ROI"(id) ON UPDATE CASCADE ON DELETE CASCADE,
	FOREIGN KEY ("POIId") REFERENCES "POI"(id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "EdgeType"(
	id INT PRIMARY KEY,
	"typeName" VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS "Edge"(
	id INT PRIMARY KEY,
	"startROI" INT,
	"endROI" INT,
	distance INT,
	coordinate VARCHAR(255),
	"typeId" INT,
	action VARCHAR(255),
	"longDescription" VARCHAR(2000),
	FOREIGN KEY ("startROI") REFERENCES "ROI"(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY ("endROI") REFERENCES "ROI"(id) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY ("typeId") REFERENCES "EdgeType"(id) ON UPDATE CASCADE ON DELETE CASCADE
	
);

CREATE TABLE IF NOT EXISTS "Photo"(
	id INT PRIMARY KEY,
	"URL" VARCHAR(2048),
	"edgeId" INT,
	FOREIGN KEY ("edgeId") REFERENCES "Edge"(id)
);

